# Generated by Django 5.1.1 on 2024-09-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_quantity'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='cart_item', to='product.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='cart_item', to='product.size'),
        ),
    ]
